defaults:
  - model:      qwen3-4B 
  - connection: default
  - dataset:    aime2025
  - override hydra/job_logging:    disabled
  - override hydra/hydra_logging:  disabled
  - _self_

load_num_of_gpu_layers: 0
experiment_name:        ${dataset.name}-${model.name}
experiment_dir:         runs/${experiment_name}
concurrent_calls:       ???