name: "Qwen/Qwen3-4B"
max_seq_length: 20000
load_in_4bit: false
dtype: "float16"
attn_implementation: "flash_attention_2"
use_gradient_checkpointing: "unsloth"

special_tokens:
  - "<ANSWER>"
  - "</ANSWER>"
  - "<CODE>"
  - "</CODE>"
  - "<COT>"
  - "</COT>"
  - "<LONG_COT>"
  - "</LONG_COT>"